### ISSUE TITLE
Does Bug Fixing Window Scale Linearly?

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/process-handbook#66]
At the moment we leave about 2 days for bug fixing in a 2 week sprint and 1 day for bug fixing in a 1 week sprint.

My question is does this definitely scale this way? Is it always 20% of the sprint time? If for some reason we did a 15 day sprint would the bug fixing window be 3 days?

**Comment by iteles** [comment]
@markwilliamfirth They're actually not 2 bug fixing days. I usually say '1 day for refactoring and 1 day for bug fixing' for simplicity but in actual fact, at least half a day if not more are taken up with sprint planning, stand ups, demo prep and the demo.

The 20% is a good rule of thumb, though requires some pragmatism in anything under 5 days.

On a side note, we'd have a 10 day sprint and a 5 day sprint rather than a 15 day one 👍

**Comment by Cleop** [comment]
@iteles - can this be closed now?

**Comment by iteles** [comment]
It can. I think it's a good question though. If anyone opens it again we can add it to the readme.
