### ISSUE TITLE
Instructions for how to use Autocrat

### ISSUE THREAD

**Issue by iteles** [dwyl/process-handbook#70]
As someone who is on the operations team,
I would like to have a set of instructions to refer to on how to use autocrat to create contracts (as mentioned in https://github.com/dwyl/process-handbook/pull/62)
So that if the people who are already aware of the processes are away or I need to refer to something because this is a task I don't carry out often, I can still create contracts if needed on short notice.

**Comment by markwilliamfirth** [comment]
@iteles the user / help guide is here: https://docs.google.com/document/d/1WTGSSlH6gwUHpipusPKLIsgfFUamDbFbJ7JaoG6-ZBo/edit#heading=h.y1q61e2vhshm

**Comment by iteles** [comment]
Thanks for the link @markwilliamfirth. Are there any particularities around how we're using it?

This URL should be added to the relevant doc before we close this issue 👍

**Comment by Cleop** [comment]
## What?

**AutoCrat** is a free chrome extension that allows you to merge document templates (e.g. invoice or contracts) with the data you wish to fill them. For example autofilling an employee's name in all of the relevant places in a new contract. 

**For its most basic functionality you require three components to use AC.** These are:
- a google document
- a google sheets spreadsheet 
- and the AC extension. 

The document is where you fill in what you want your template to include. The spreadsheet includes all of your instances of data e.g. the data for all of the employees you want to create contracts for. You must add AC to Chrome in order to run it on your spreadsheet. Finally you will end up with a customised pdf or document.

## Buzzwords 🐝 / Terminology
- **"Project"** = a spreadsheet
- **"Job"** = a set of instructions telling AutoCrat what to do.  When you run a job, a new merge is created.
- **"Template"** = your google sheet or whatever it is that you want the data to be filled in on
- **"Tags"** =  tags are the words that you want to customise in your template. You create tags by wrapping a word in arrows like this: `<<name>>`. The word you put between the arrows is what should correspond with the column title in your "project" (your google sheet). Matching is case sensitive. It is through matching the tag values that your template is filled in. It is possible to name your tags and columns differently but to do this you must then indicate which should correspond with one another when setting up a job. You can even use tags to give the resulting document a customised auto-generated name.

## Getting Started

1. Open the spreadsheet in which you wish to store the data that will customise/fill your template. Start AutoCrat by clicking “Open” from the AutoCrat menu under Add-ons in your spreadsheet. If this is your first time then you'll only have the option to "install" AC if you're on a file which has used it before but you've not yet installed it on your device. Click install and then 'allow' to give AC permission to run.
<img src="https://user-images.githubusercontent.com/16775804/33445527-fb5a1842-d5f4-11e7-9f8c-5d6dd06bf99a.png" width=350px />
Then reopen the dropdown and instead of install you should now have the option to click "Open", so now do so. This should then load a window something like this:

<img src="https://user-images.githubusercontent.com/16775804/33445684-8398dfa4-d5f5-11e7-88d7-377f85ad426c.png" width=400px />

In this case you can see an existing job 'Member Agreement' and we have the option to create another new job.

2. Click the “New Job” button OR the little pencil icon on an existing job and the job editor wizard will open. 

3. Name your merge job - Give your job a useful name that indicates what running it achieves - ie. new employee contract

4. Choose template - Choose the document that you want to merge your spreadsheet data with from your google drive.

5. Map Source Data to Template - When setting up your merge you will need to “map” (i.e. match) the tags in your document template to the columns in your spreadsheet. Remember that if the tags match their corresponding header exactly, the mapping will be done automatically.  But they do not need to match, in which case you must manually match them. 

6. File Settings - 
  - **File Name:** This is the name that each merged document will be given.  Use <<tags>> that match a column header to make the names unique.  Use <<NOW>> or <<TODAY>> to give each doc a timestamp. 
  - **File Type:** what do you want your end files to be saved as? Either Google Document or PDF.  
  - **Output as**: Choose to output one document per row of data that satisfies your merge condition, or a single document with each row merged into the same document.

7. Choose destination folder(s)
Choose a folder for every merged document to be dropped into. This is actually optional IF you include a “dynamic folder reference”.

8. Add dynamic folder reference (optional)
AutoCrat always provided this functionality, but it’s being renamed for clarity.  It was formerly referred to as a “Secondary Folder Key”, which isn’t super clear.  

The idea is that sometimes you want a merged doc to be dropped into certain folders and not others.  E.g. Say you want to create a document for each teacher at your school and organize those docs by grade team.  Create a folder for each team, put the proper folder ID into a column in your data sheet, and then tell AutoCrat which column contains these “dynamic” folder references.
  7. Set Merge Condition (Optional)
A merge condition tells AutoCrat whether or not to merge a particular row of data.  By default, AutoCrat will run for all rows in a job’s data sheet that do not have a value in the status column for that job.  You can optionally add additional conditions that must be met for AutoCrat to include a row of data.  

Specifically, you can tell AutoCrat to only merge a row of data IF the value for a specified column is equal to a particular value, is NULL or is NOT NULL.  NULL means empty or blank, and NOT NULL means not empty or blank (i.e. it has any value at all).  You should NOT include quotes around the value.

AutoCrat v2 only let you add a single condition, but AutoCrat v3 now allows for multiple.
  9. Share docs & send emails
Currently, if you want to share a merged document with others, you must also send them an email. The merged document will be shared with each email recipient.  You can optionally prevent editors from re-sharing the merged doc and/or send the email from a generic no-reply email address (e.g. no-reply@myschool.org).
  10. Add/remove job triggers
Optionally tell AutoCrat to run every time a form is submitted (only works if there is a form attached to the spreadsheet.  And/or to run at a given time interval (E.g. every 3 hours).  Note: A limitation of Google Add-ons is that they cannot run more frequently than every hour.  Check out Understanding Triggers in AutoCrat3 for further reading.

**Comment by iteles** [comment]
Closing this as no longer relevant given we have moved away from this system: see https://github.com/dwyl/process-handbook/issues/97 (and the MANY annoying bugs this caused).

Thanks again for the great work in documenting this @Cleop :blush: Very findable and useful! Exactly what we were looking for with this issue.

**Comment by himanshu-03** [comment]
Hello I am not able to see the file name with the help of <<TAGS>>

![image](https://user-images.githubusercontent.com/97957777/231794258-8ce90e06-eb74-404b-a41c-8160f48a34b1.png)

![image](https://user-images.githubusercontent.com/97957777/231794301-388a3c4b-bc80-4727-8a13-8688638bc7f5.png)

Can anyone help?
